name: Node JS Video Downloader

on:
  workflow_dispatch:

jobs:
  run-extractor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install FFmpeg # إضافة هذه الخطوة ضرورية لدمج الفيديو
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install yt-dlp
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Run Script
        run: node index.js

      # خطوة إضافية: لكي ترى الملف الناتج في GitHub وتستطيع تحميله
      - name: Upload Video Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-video-file
          path: video_to_upload.mp4
